/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The root schema comprises the entire JSON document.
 */
export interface TheRootEVDCConfigurationSchema {
  $schema: string;
  baseUrl: string;
  /**
   * Environment informations object
   */
  env: {
    /**
     * the name of the environment (staging, preview-commitHash, production)
     */
    name?: string;
    /**
     * Application version, should be either the current commit hash, either a git tag
     */
    version?: string;
    /**
     * Key for the map provider
     */
    mapApiKey?: string;
    /**
     * Authentication client id for OIDC authentication
     */
    authClientId?: string;
    [k: string]: unknown;
  };
  /**
   * map of enabled features for this environment
   */
  features?: {
    type?: "login" | "mapView";
    [k: string]: unknown;
  };
}
